//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CitySquaresModel", "DealID", "Deal", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CitySquaresInsider.Data.Deal), "Voucher", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CitySquaresInsider.Data.Voucher), true)]
[assembly: EdmRelationshipAttribute("CitySquaresModel", "MerchantID", "Merchant", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CitySquaresInsider.Data.Merchant), "Deal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CitySquaresInsider.Data.Deal), true)]

#endregion

namespace CitySquaresInsider.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CitySquaresModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CitySquaresModelContainer object using the connection string found in the 'CitySquaresModelContainer' section of the application configuration file.
        /// </summary>
        public CitySquaresModelContainer() : base("name=CitySquaresModelContainer", "CitySquaresModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CitySquaresModelContainer object.
        /// </summary>
        public CitySquaresModelContainer(string connectionString) : base(connectionString, "CitySquaresModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CitySquaresModelContainer object.
        /// </summary>
        public CitySquaresModelContainer(EntityConnection connection) : base(connection, "CitySquaresModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Address> Addresses
        {
            get
            {
                if ((_Addresses == null))
                {
                    _Addresses = base.CreateObjectSet<Address>("Addresses");
                }
                return _Addresses;
            }
        }
        private ObjectSet<Address> _Addresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConsumerFBData> ConsumerFBDatas
        {
            get
            {
                if ((_ConsumerFBDatas == null))
                {
                    _ConsumerFBDatas = base.CreateObjectSet<ConsumerFBData>("ConsumerFBDatas");
                }
                return _ConsumerFBDatas;
            }
        }
        private ObjectSet<ConsumerFBData> _ConsumerFBDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Consumer> Consumers
        {
            get
            {
                if ((_Consumers == null))
                {
                    _Consumers = base.CreateObjectSet<Consumer>("Consumers");
                }
                return _Consumers;
            }
        }
        private ObjectSet<Consumer> _Consumers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Deal> Deals
        {
            get
            {
                if ((_Deals == null))
                {
                    _Deals = base.CreateObjectSet<Deal>("Deals");
                }
                return _Deals;
            }
        }
        private ObjectSet<Deal> _Deals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FacebookData> FacebookDatas
        {
            get
            {
                if ((_FacebookDatas == null))
                {
                    _FacebookDatas = base.CreateObjectSet<FacebookData>("FacebookDatas");
                }
                return _FacebookDatas;
            }
        }
        private ObjectSet<FacebookData> _FacebookDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Merchant> Merchants
        {
            get
            {
                if ((_Merchants == null))
                {
                    _Merchants = base.CreateObjectSet<Merchant>("Merchants");
                }
                return _Merchants;
            }
        }
        private ObjectSet<Merchant> _Merchants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PaymentStatus> PaymentStatuses
        {
            get
            {
                if ((_PaymentStatuses == null))
                {
                    _PaymentStatuses = base.CreateObjectSet<PaymentStatus>("PaymentStatuses");
                }
                return _PaymentStatuses;
            }
        }
        private ObjectSet<PaymentStatus> _PaymentStatuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Phone> Phones
        {
            get
            {
                if ((_Phones == null))
                {
                    _Phones = base.CreateObjectSet<Phone>("Phones");
                }
                return _Phones;
            }
        }
        private ObjectSet<Phone> _Phones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Voucher> Vouchers
        {
            get
            {
                if ((_Vouchers == null))
                {
                    _Vouchers = base.CreateObjectSet<Voucher>("Vouchers");
                }
                return _Vouchers;
            }
        }
        private ObjectSet<Voucher> _Vouchers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AppToken> AppTokens
        {
            get
            {
                if ((_AppTokens == null))
                {
                    _AppTokens = base.CreateObjectSet<AppToken>("AppTokens");
                }
                return _AppTokens;
            }
        }
        private ObjectSet<AppToken> _AppTokens;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Addresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddresses(Address address)
        {
            base.AddObject("Addresses", address);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConsumerFBDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsumerFBDatas(ConsumerFBData consumerFBData)
        {
            base.AddObject("ConsumerFBDatas", consumerFBData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Consumers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsumers(Consumer consumer)
        {
            base.AddObject("Consumers", consumer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Deals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDeals(Deal deal)
        {
            base.AddObject("Deals", deal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FacebookDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacebookDatas(FacebookData facebookData)
        {
            base.AddObject("FacebookDatas", facebookData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Merchants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMerchants(Merchant merchant)
        {
            base.AddObject("Merchants", merchant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PaymentStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaymentStatuses(PaymentStatus paymentStatus)
        {
            base.AddObject("PaymentStatuses", paymentStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Phones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhones(Phone phone)
        {
            base.AddObject("Phones", phone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vouchers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVouchers(Voucher voucher)
        {
            base.AddObject("Vouchers", voucher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AppTokens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppTokens(AppToken appToken)
        {
            base.AddObject("AppTokens", appToken);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="Address")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Address : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="addressID">Initial value of the AddressID property.</param>
        /// <param name="address1">Initial value of the Address1 property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="zip">Initial value of the Zip property.</param>
        public static Address CreateAddress(global::System.Int64 addressID, global::System.String address1, global::System.String city, global::System.String state, global::System.String zip)
        {
            Address address = new Address();
            address.AddressID = addressID;
            address.Address1 = address1;
            address.City = city;
            address.State = state;
            address.Zip = zip;
            return address;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AddressID
        {
            get
            {
                return _AddressID;
            }
            set
            {
                if (_AddressID != value)
                {
                    OnAddressIDChanging(value);
                    ReportPropertyChanging("AddressID");
                    _AddressID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AddressID");
                    OnAddressIDChanged();
                }
            }
        }
        private global::System.Int64 _AddressID;
        partial void OnAddressIDChanging(global::System.Int64 value);
        partial void OnAddressIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="AppToken")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppToken : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AppToken object.
        /// </summary>
        /// <param name="appTokenID">Initial value of the AppTokenID property.</param>
        /// <param name="label">Initial value of the Label property.</param>
        /// <param name="token">Initial value of the Token property.</param>
        public static AppToken CreateAppToken(global::System.Int32 appTokenID, global::System.String label, global::System.String token)
        {
            AppToken appToken = new AppToken();
            appToken.AppTokenID = appTokenID;
            appToken.Label = label;
            appToken.Token = token;
            return appToken;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppTokenID
        {
            get
            {
                return _AppTokenID;
            }
            set
            {
                if (_AppTokenID != value)
                {
                    OnAppTokenIDChanging(value);
                    ReportPropertyChanging("AppTokenID");
                    _AppTokenID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppTokenID");
                    OnAppTokenIDChanged();
                }
            }
        }
        private global::System.Int32 _AppTokenID;
        partial void OnAppTokenIDChanging(global::System.Int32 value);
        partial void OnAppTokenIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="Consumer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Consumer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Consumer object.
        /// </summary>
        /// <param name="consumersID">Initial value of the ConsumersID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="facebookID">Initial value of the FacebookID property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="lastLoggedIn">Initial value of the LastLoggedIn property.</param>
        public static Consumer CreateConsumer(global::System.Int64 consumersID, global::System.String name, global::System.Int64 facebookID, global::System.String email, global::System.DateTime dateCreated, global::System.DateTime lastLoggedIn)
        {
            Consumer consumer = new Consumer();
            consumer.ConsumersID = consumersID;
            consumer.Name = name;
            consumer.FacebookID = facebookID;
            consumer.Email = email;
            consumer.DateCreated = dateCreated;
            consumer.LastLoggedIn = lastLoggedIn;
            return consumer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ConsumersID
        {
            get
            {
                return _ConsumersID;
            }
            set
            {
                if (_ConsumersID != value)
                {
                    OnConsumersIDChanging(value);
                    ReportPropertyChanging("ConsumersID");
                    _ConsumersID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConsumersID");
                    OnConsumersIDChanged();
                }
            }
        }
        private global::System.Int64 _ConsumersID;
        partial void OnConsumersIDChanging(global::System.Int64 value);
        partial void OnConsumersIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FacebookID
        {
            get
            {
                return _FacebookID;
            }
            set
            {
                OnFacebookIDChanging(value);
                ReportPropertyChanging("FacebookID");
                _FacebookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacebookID");
                OnFacebookIDChanged();
            }
        }
        private global::System.Int64 _FacebookID;
        partial void OnFacebookIDChanging(global::System.Int64 value);
        partial void OnFacebookIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUpdated;
        partial void OnDateUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastLoggedIn
        {
            get
            {
                return _LastLoggedIn;
            }
            set
            {
                OnLastLoggedInChanging(value);
                ReportPropertyChanging("LastLoggedIn");
                _LastLoggedIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoggedIn");
                OnLastLoggedInChanged();
            }
        }
        private global::System.DateTime _LastLoggedIn;
        partial void OnLastLoggedInChanging(global::System.DateTime value);
        partial void OnLastLoggedInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AddressID
        {
            get
            {
                return _AddressID;
            }
            set
            {
                OnAddressIDChanging(value);
                ReportPropertyChanging("AddressID");
                _AddressID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddressID");
                OnAddressIDChanged();
            }
        }
        private Nullable<global::System.Int64> _AddressID;
        partial void OnAddressIDChanging(Nullable<global::System.Int64> value);
        partial void OnAddressIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PhoneID
        {
            get
            {
                return _PhoneID;
            }
            set
            {
                OnPhoneIDChanging(value);
                ReportPropertyChanging("PhoneID");
                _PhoneID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhoneID");
                OnPhoneIDChanged();
            }
        }
        private Nullable<global::System.Int64> _PhoneID;
        partial void OnPhoneIDChanging(Nullable<global::System.Int64> value);
        partial void OnPhoneIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="ConsumerFBData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConsumerFBData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConsumerFBData object.
        /// </summary>
        /// <param name="consumerID">Initial value of the ConsumerID property.</param>
        /// <param name="fBDataID">Initial value of the FBDataID property.</param>
        public static ConsumerFBData CreateConsumerFBData(global::System.Int64 consumerID, global::System.Int64 fBDataID)
        {
            ConsumerFBData consumerFBData = new ConsumerFBData();
            consumerFBData.ConsumerID = consumerID;
            consumerFBData.FBDataID = fBDataID;
            return consumerFBData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ConsumerID
        {
            get
            {
                return _ConsumerID;
            }
            set
            {
                if (_ConsumerID != value)
                {
                    OnConsumerIDChanging(value);
                    ReportPropertyChanging("ConsumerID");
                    _ConsumerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConsumerID");
                    OnConsumerIDChanged();
                }
            }
        }
        private global::System.Int64 _ConsumerID;
        partial void OnConsumerIDChanging(global::System.Int64 value);
        partial void OnConsumerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FBDataID
        {
            get
            {
                return _FBDataID;
            }
            set
            {
                if (_FBDataID != value)
                {
                    OnFBDataIDChanging(value);
                    ReportPropertyChanging("FBDataID");
                    _FBDataID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FBDataID");
                    OnFBDataIDChanged();
                }
            }
        }
        private global::System.Int64 _FBDataID;
        partial void OnFBDataIDChanging(global::System.Int64 value);
        partial void OnFBDataIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="Deal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Deal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Deal object.
        /// </summary>
        /// <param name="dealID">Initial value of the DealID property.</param>
        /// <param name="normalCost">Initial value of the NormalCost property.</param>
        /// <param name="discount">Initial value of the Discount property.</param>
        /// <param name="monthlyCost">Initial value of the MonthlyCost property.</param>
        /// <param name="commission">Initial value of the Commission property.</param>
        /// <param name="vouchersPerPeriod">Initial value of the VouchersPerPeriod property.</param>
        /// <param name="merchantID">Initial value of the MerchantID property.</param>
        public static Deal CreateDeal(global::System.Int64 dealID, global::System.Decimal normalCost, global::System.Decimal discount, global::System.Decimal monthlyCost, global::System.Decimal commission, global::System.Decimal vouchersPerPeriod, global::System.Int64 merchantID)
        {
            Deal deal = new Deal();
            deal.DealID = dealID;
            deal.NormalCost = normalCost;
            deal.Discount = discount;
            deal.MonthlyCost = monthlyCost;
            deal.Commission = commission;
            deal.VouchersPerPeriod = vouchersPerPeriod;
            deal.MerchantID = merchantID;
            return deal;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DealID
        {
            get
            {
                return _DealID;
            }
            set
            {
                if (_DealID != value)
                {
                    OnDealIDChanging(value);
                    ReportPropertyChanging("DealID");
                    _DealID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DealID");
                    OnDealIDChanged();
                }
            }
        }
        private global::System.Int64 _DealID;
        partial void OnDealIDChanging(global::System.Int64 value);
        partial void OnDealIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NormalCost
        {
            get
            {
                return _NormalCost;
            }
            set
            {
                OnNormalCostChanging(value);
                ReportPropertyChanging("NormalCost");
                _NormalCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NormalCost");
                OnNormalCostChanged();
            }
        }
        private global::System.Decimal _NormalCost;
        partial void OnNormalCostChanging(global::System.Decimal value);
        partial void OnNormalCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                OnDiscountChanging(value);
                ReportPropertyChanging("Discount");
                _Discount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discount");
                OnDiscountChanged();
            }
        }
        private global::System.Decimal _Discount;
        partial void OnDiscountChanging(global::System.Decimal value);
        partial void OnDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MonthlyCost
        {
            get
            {
                return _MonthlyCost;
            }
            set
            {
                OnMonthlyCostChanging(value);
                ReportPropertyChanging("MonthlyCost");
                _MonthlyCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MonthlyCost");
                OnMonthlyCostChanged();
            }
        }
        private global::System.Decimal _MonthlyCost;
        partial void OnMonthlyCostChanging(global::System.Decimal value);
        partial void OnMonthlyCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Commission
        {
            get
            {
                return _Commission;
            }
            set
            {
                OnCommissionChanging(value);
                ReportPropertyChanging("Commission");
                _Commission = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Commission");
                OnCommissionChanged();
            }
        }
        private global::System.Decimal _Commission;
        partial void OnCommissionChanging(global::System.Decimal value);
        partial void OnCommissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VouchersPerPeriod
        {
            get
            {
                return _VouchersPerPeriod;
            }
            set
            {
                OnVouchersPerPeriodChanging(value);
                ReportPropertyChanging("VouchersPerPeriod");
                _VouchersPerPeriod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VouchersPerPeriod");
                OnVouchersPerPeriodChanged();
            }
        }
        private global::System.Decimal _VouchersPerPeriod;
        partial void OnVouchersPerPeriodChanging(global::System.Decimal value);
        partial void OnVouchersPerPeriodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MerchantID
        {
            get
            {
                return _MerchantID;
            }
            set
            {
                OnMerchantIDChanging(value);
                ReportPropertyChanging("MerchantID");
                _MerchantID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MerchantID");
                OnMerchantIDChanged();
            }
        }
        private global::System.Int64 _MerchantID;
        partial void OnMerchantIDChanging(global::System.Int64 value);
        partial void OnMerchantIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CitySquaresModel", "DealID", "Voucher")]
        public EntityCollection<Voucher> Vouchers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Voucher>("CitySquaresModel.DealID", "Voucher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Voucher>("CitySquaresModel.DealID", "Voucher", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CitySquaresModel", "MerchantID", "Merchant")]
        public Merchant Merchant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchant>("CitySquaresModel.MerchantID", "Merchant").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchant>("CitySquaresModel.MerchantID", "Merchant").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Merchant> MerchantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchant>("CitySquaresModel.MerchantID", "Merchant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Merchant>("CitySquaresModel.MerchantID", "Merchant", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="FacebookData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FacebookData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FacebookData object.
        /// </summary>
        /// <param name="fBDataID">Initial value of the FBDataID property.</param>
        /// <param name="fieldName">Initial value of the FieldName property.</param>
        public static FacebookData CreateFacebookData(global::System.Int64 fBDataID, global::System.String fieldName)
        {
            FacebookData facebookData = new FacebookData();
            facebookData.FBDataID = fBDataID;
            facebookData.FieldName = fieldName;
            return facebookData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FBDataID
        {
            get
            {
                return _FBDataID;
            }
            set
            {
                if (_FBDataID != value)
                {
                    OnFBDataIDChanging(value);
                    ReportPropertyChanging("FBDataID");
                    _FBDataID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FBDataID");
                    OnFBDataIDChanged();
                }
            }
        }
        private global::System.Int64 _FBDataID;
        partial void OnFBDataIDChanging(global::System.Int64 value);
        partial void OnFBDataIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FieldName
        {
            get
            {
                return _FieldName;
            }
            set
            {
                OnFieldNameChanging(value);
                ReportPropertyChanging("FieldName");
                _FieldName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FieldName");
                OnFieldNameChanged();
            }
        }
        private global::System.String _FieldName;
        partial void OnFieldNameChanging(global::System.String value);
        partial void OnFieldNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="Merchant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Merchant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Merchant object.
        /// </summary>
        /// <param name="merchantID">Initial value of the MerchantID property.</param>
        /// <param name="businessName">Initial value of the BusinessName property.</param>
        /// <param name="bizAddressID">Initial value of the BizAddressID property.</param>
        /// <param name="bizPhoneID">Initial value of the BizPhoneID property.</param>
        /// <param name="facebookID">Initial value of the FacebookID property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static Merchant CreateMerchant(global::System.Int64 merchantID, global::System.String businessName, global::System.Int64 bizAddressID, global::System.Int64 bizPhoneID, global::System.Int64 facebookID, global::System.DateTime dateCreated)
        {
            Merchant merchant = new Merchant();
            merchant.MerchantID = merchantID;
            merchant.BusinessName = businessName;
            merchant.BizAddressID = bizAddressID;
            merchant.BizPhoneID = bizPhoneID;
            merchant.FacebookID = facebookID;
            merchant.DateCreated = dateCreated;
            return merchant;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MerchantID
        {
            get
            {
                return _MerchantID;
            }
            set
            {
                if (_MerchantID != value)
                {
                    OnMerchantIDChanging(value);
                    ReportPropertyChanging("MerchantID");
                    _MerchantID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MerchantID");
                    OnMerchantIDChanged();
                }
            }
        }
        private global::System.Int64 _MerchantID;
        partial void OnMerchantIDChanging(global::System.Int64 value);
        partial void OnMerchantIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BusinessName
        {
            get
            {
                return _BusinessName;
            }
            set
            {
                OnBusinessNameChanging(value);
                ReportPropertyChanging("BusinessName");
                _BusinessName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BusinessName");
                OnBusinessNameChanged();
            }
        }
        private global::System.String _BusinessName;
        partial void OnBusinessNameChanging(global::System.String value);
        partial void OnBusinessNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 BizAddressID
        {
            get
            {
                return _BizAddressID;
            }
            set
            {
                OnBizAddressIDChanging(value);
                ReportPropertyChanging("BizAddressID");
                _BizAddressID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BizAddressID");
                OnBizAddressIDChanged();
            }
        }
        private global::System.Int64 _BizAddressID;
        partial void OnBizAddressIDChanging(global::System.Int64 value);
        partial void OnBizAddressIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 BizPhoneID
        {
            get
            {
                return _BizPhoneID;
            }
            set
            {
                OnBizPhoneIDChanging(value);
                ReportPropertyChanging("BizPhoneID");
                _BizPhoneID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BizPhoneID");
                OnBizPhoneIDChanged();
            }
        }
        private global::System.Int64 _BizPhoneID;
        partial void OnBizPhoneIDChanging(global::System.Int64 value);
        partial void OnBizPhoneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ContactPhoneID
        {
            get
            {
                return _ContactPhoneID;
            }
            set
            {
                OnContactPhoneIDChanging(value);
                ReportPropertyChanging("ContactPhoneID");
                _ContactPhoneID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContactPhoneID");
                OnContactPhoneIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ContactPhoneID;
        partial void OnContactPhoneIDChanging(Nullable<global::System.Int64> value);
        partial void OnContactPhoneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AltPhoneID
        {
            get
            {
                return _AltPhoneID;
            }
            set
            {
                OnAltPhoneIDChanging(value);
                ReportPropertyChanging("AltPhoneID");
                _AltPhoneID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AltPhoneID");
                OnAltPhoneIDChanged();
            }
        }
        private Nullable<global::System.Int64> _AltPhoneID;
        partial void OnAltPhoneIDChanging(Nullable<global::System.Int64> value);
        partial void OnAltPhoneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PaymentAddrID
        {
            get
            {
                return _PaymentAddrID;
            }
            set
            {
                OnPaymentAddrIDChanging(value);
                ReportPropertyChanging("PaymentAddrID");
                _PaymentAddrID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentAddrID");
                OnPaymentAddrIDChanged();
            }
        }
        private Nullable<global::System.Int64> _PaymentAddrID;
        partial void OnPaymentAddrIDChanging(Nullable<global::System.Int64> value);
        partial void OnPaymentAddrIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BizURL
        {
            get
            {
                return _BizURL;
            }
            set
            {
                OnBizURLChanging(value);
                ReportPropertyChanging("BizURL");
                _BizURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BizURL");
                OnBizURLChanged();
            }
        }
        private global::System.String _BizURL;
        partial void OnBizURLChanging(global::System.String value);
        partial void OnBizURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FacebookID
        {
            get
            {
                return _FacebookID;
            }
            set
            {
                OnFacebookIDChanging(value);
                ReportPropertyChanging("FacebookID");
                _FacebookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacebookID");
                OnFacebookIDChanged();
            }
        }
        private global::System.Int64 _FacebookID;
        partial void OnFacebookIDChanging(global::System.Int64 value);
        partial void OnFacebookIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUpdated;
        partial void OnDateUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoggedIn
        {
            get
            {
                return _LastLoggedIn;
            }
            set
            {
                OnLastLoggedInChanging(value);
                ReportPropertyChanging("LastLoggedIn");
                _LastLoggedIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoggedIn");
                OnLastLoggedInChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoggedIn;
        partial void OnLastLoggedInChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoggedInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BizEmail
        {
            get
            {
                return _BizEmail;
            }
            set
            {
                OnBizEmailChanging(value);
                ReportPropertyChanging("BizEmail");
                _BizEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BizEmail");
                OnBizEmailChanged();
            }
        }
        private global::System.String _BizEmail;
        partial void OnBizEmailChanging(global::System.String value);
        partial void OnBizEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactEmail
        {
            get
            {
                return _ContactEmail;
            }
            set
            {
                OnContactEmailChanging(value);
                ReportPropertyChanging("ContactEmail");
                _ContactEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactEmail");
                OnContactEmailChanged();
            }
        }
        private global::System.String _ContactEmail;
        partial void OnContactEmailChanging(global::System.String value);
        partial void OnContactEmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CitySquaresModel", "MerchantID", "Deal")]
        public EntityCollection<Deal> Deals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Deal>("CitySquaresModel.MerchantID", "Deal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Deal>("CitySquaresModel.MerchantID", "Deal", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="PaymentStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PaymentStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PaymentStatus object.
        /// </summary>
        /// <param name="paymentStatusID">Initial value of the PaymentStatusID property.</param>
        /// <param name="consumerID">Initial value of the ConsumerID property.</param>
        /// <param name="voucherID">Initial value of the VoucherID property.</param>
        /// <param name="paymentType">Initial value of the PaymentType property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="paymentDate">Initial value of the PaymentDate property.</param>
        public static PaymentStatus CreatePaymentStatus(global::System.Int64 paymentStatusID, global::System.Int64 consumerID, global::System.Int64 voucherID, global::System.Int32 paymentType, global::System.Int32 status, global::System.Decimal amount, global::System.DateTime paymentDate)
        {
            PaymentStatus paymentStatus = new PaymentStatus();
            paymentStatus.PaymentStatusID = paymentStatusID;
            paymentStatus.ConsumerID = consumerID;
            paymentStatus.VoucherID = voucherID;
            paymentStatus.PaymentType = paymentType;
            paymentStatus.Status = status;
            paymentStatus.Amount = amount;
            paymentStatus.PaymentDate = paymentDate;
            return paymentStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PaymentStatusID
        {
            get
            {
                return _PaymentStatusID;
            }
            set
            {
                if (_PaymentStatusID != value)
                {
                    OnPaymentStatusIDChanging(value);
                    ReportPropertyChanging("PaymentStatusID");
                    _PaymentStatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaymentStatusID");
                    OnPaymentStatusIDChanged();
                }
            }
        }
        private global::System.Int64 _PaymentStatusID;
        partial void OnPaymentStatusIDChanging(global::System.Int64 value);
        partial void OnPaymentStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ConsumerID
        {
            get
            {
                return _ConsumerID;
            }
            set
            {
                OnConsumerIDChanging(value);
                ReportPropertyChanging("ConsumerID");
                _ConsumerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsumerID");
                OnConsumerIDChanged();
            }
        }
        private global::System.Int64 _ConsumerID;
        partial void OnConsumerIDChanging(global::System.Int64 value);
        partial void OnConsumerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransactionID
        {
            get
            {
                return _TransactionID;
            }
            set
            {
                OnTransactionIDChanging(value);
                ReportPropertyChanging("TransactionID");
                _TransactionID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransactionID");
                OnTransactionIDChanged();
            }
        }
        private global::System.String _TransactionID;
        partial void OnTransactionIDChanging(global::System.String value);
        partial void OnTransactionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 VoucherID
        {
            get
            {
                return _VoucherID;
            }
            set
            {
                OnVoucherIDChanging(value);
                ReportPropertyChanging("VoucherID");
                _VoucherID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VoucherID");
                OnVoucherIDChanged();
            }
        }
        private global::System.Int64 _VoucherID;
        partial void OnVoucherIDChanging(global::System.Int64 value);
        partial void OnVoucherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaymentType
        {
            get
            {
                return _PaymentType;
            }
            set
            {
                OnPaymentTypeChanging(value);
                ReportPropertyChanging("PaymentType");
                _PaymentType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentType");
                OnPaymentTypeChanged();
            }
        }
        private global::System.Int32 _PaymentType;
        partial void OnPaymentTypeChanging(global::System.Int32 value);
        partial void OnPaymentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PaymentDate
        {
            get
            {
                return _PaymentDate;
            }
            set
            {
                OnPaymentDateChanging(value);
                ReportPropertyChanging("PaymentDate");
                _PaymentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentDate");
                OnPaymentDateChanged();
            }
        }
        private global::System.DateTime _PaymentDate;
        partial void OnPaymentDateChanging(global::System.DateTime value);
        partial void OnPaymentDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="Phone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Phone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Phone object.
        /// </summary>
        /// <param name="phoneID">Initial value of the PhoneID property.</param>
        /// <param name="phone1">Initial value of the Phone1 property.</param>
        /// <param name="phoneType">Initial value of the PhoneType property.</param>
        public static Phone CreatePhone(global::System.Int64 phoneID, global::System.String phone1, global::System.Int32 phoneType)
        {
            Phone phone = new Phone();
            phone.PhoneID = phoneID;
            phone.Phone1 = phone1;
            phone.PhoneType = phoneType;
            return phone;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PhoneID
        {
            get
            {
                return _PhoneID;
            }
            set
            {
                if (_PhoneID != value)
                {
                    OnPhoneIDChanging(value);
                    ReportPropertyChanging("PhoneID");
                    _PhoneID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PhoneID");
                    OnPhoneIDChanged();
                }
            }
        }
        private global::System.Int64 _PhoneID;
        partial void OnPhoneIDChanging(global::System.Int64 value);
        partial void OnPhoneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone1
        {
            get
            {
                return _Phone1;
            }
            set
            {
                OnPhone1Changing(value);
                ReportPropertyChanging("Phone1");
                _Phone1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone1");
                OnPhone1Changed();
            }
        }
        private global::System.String _Phone1;
        partial void OnPhone1Changing(global::System.String value);
        partial void OnPhone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PhoneType
        {
            get
            {
                return _PhoneType;
            }
            set
            {
                OnPhoneTypeChanging(value);
                ReportPropertyChanging("PhoneType");
                _PhoneType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhoneType");
                OnPhoneTypeChanged();
            }
        }
        private global::System.Int32 _PhoneType;
        partial void OnPhoneTypeChanging(global::System.Int32 value);
        partial void OnPhoneTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CitySquaresModel", Name="Voucher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Voucher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Voucher object.
        /// </summary>
        /// <param name="voucherID">Initial value of the VoucherID property.</param>
        /// <param name="consumerID">Initial value of the ConsumerID property.</param>
        /// <param name="dealID">Initial value of the DealID property.</param>
        /// <param name="used">Initial value of the Used property.</param>
        /// <param name="datePurchased">Initial value of the DatePurchased property.</param>
        public static Voucher CreateVoucher(global::System.Int64 voucherID, global::System.Int64 consumerID, global::System.Int64 dealID, global::System.Boolean used, global::System.DateTime datePurchased)
        {
            Voucher voucher = new Voucher();
            voucher.VoucherID = voucherID;
            voucher.ConsumerID = consumerID;
            voucher.DealID = dealID;
            voucher.Used = used;
            voucher.DatePurchased = datePurchased;
            return voucher;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 VoucherID
        {
            get
            {
                return _VoucherID;
            }
            set
            {
                if (_VoucherID != value)
                {
                    OnVoucherIDChanging(value);
                    ReportPropertyChanging("VoucherID");
                    _VoucherID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VoucherID");
                    OnVoucherIDChanged();
                }
            }
        }
        private global::System.Int64 _VoucherID;
        partial void OnVoucherIDChanging(global::System.Int64 value);
        partial void OnVoucherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ConsumerID
        {
            get
            {
                return _ConsumerID;
            }
            set
            {
                OnConsumerIDChanging(value);
                ReportPropertyChanging("ConsumerID");
                _ConsumerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsumerID");
                OnConsumerIDChanged();
            }
        }
        private global::System.Int64 _ConsumerID;
        partial void OnConsumerIDChanging(global::System.Int64 value);
        partial void OnConsumerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DealID
        {
            get
            {
                return _DealID;
            }
            set
            {
                OnDealIDChanging(value);
                ReportPropertyChanging("DealID");
                _DealID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealID");
                OnDealIDChanged();
            }
        }
        private global::System.Int64 _DealID;
        partial void OnDealIDChanging(global::System.Int64 value);
        partial void OnDealIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Used
        {
            get
            {
                return _Used;
            }
            set
            {
                OnUsedChanging(value);
                ReportPropertyChanging("Used");
                _Used = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Used");
                OnUsedChanged();
            }
        }
        private global::System.Boolean _Used;
        partial void OnUsedChanging(global::System.Boolean value);
        partial void OnUsedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUsed
        {
            get
            {
                return _DateUsed;
            }
            set
            {
                OnDateUsedChanging(value);
                ReportPropertyChanging("DateUsed");
                _DateUsed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUsed");
                OnDateUsedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUsed;
        partial void OnDateUsedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUsedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DatePurchased
        {
            get
            {
                return _DatePurchased;
            }
            set
            {
                OnDatePurchasedChanging(value);
                ReportPropertyChanging("DatePurchased");
                _DatePurchased = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatePurchased");
                OnDatePurchasedChanged();
            }
        }
        private global::System.DateTime _DatePurchased;
        partial void OnDatePurchasedChanging(global::System.DateTime value);
        partial void OnDatePurchasedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CitySquaresModel", "DealID", "Deal")]
        public Deal Deal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Deal>("CitySquaresModel.DealID", "Deal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Deal>("CitySquaresModel.DealID", "Deal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Deal> DealReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Deal>("CitySquaresModel.DealID", "Deal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Deal>("CitySquaresModel.DealID", "Deal", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
